# Generated by Django 3.2.16 on 2022-11-02 19:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sistema', '0003_auto_20221014_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2022, 11, 2, 16, 39, 55, 647472)),
        ),
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField(default=datetime.datetime(2022, 11, 2, 16, 39, 55, 648471))),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.pedido')),
            ],
        ),
    ]
